export const categories = [
  {
    id: 1,
    slug: "educational",
    name: "Educational Toys",
    nameAr: "ألعاب تعليمية",
    description: "Smart toys that make learning fun",
    descriptionAr: "ألعاب ذكية تجعل التعلم ممتعاً",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80",
    count: 128,
    color: "from-blue-400 to-blue-600",
  },
  {
    id: 2,
    slug: "outdoor",
    name: "Outdoor Toys",
    nameAr: "ألعاب خارجية",
    description: "Active play for energetic kids",
    descriptionAr: "لعب نشط للأطفال النشيطين",
    image: "https://images.unsplash.com/photo-1566438480900-0609be27a4be?w=600&q=80",
    count: 95,
    color: "from-green-400 to-green-600",
  },
  {
    id: 3,
    slug: "baby",
    name: "Baby Toys",
    nameAr: "ألعاب الأطفال الرضع",
    description: "Safe and stimulating for infants",
    descriptionAr: "آمنة ومحفزة للرضع",
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80",
    count: 74,
    color: "from-pink-400 to-pink-600",
  },
  {
    id: 4,
    slug: "electronic",
    name: "Electronic Toys",
    nameAr: "ألعاب إلكترونية",
    description: "Tech-powered interactive fun",
    descriptionAr: "متعة تفاعلية مدعومة بالتكنولوجيا",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    count: 112,
    color: "from-purple-400 to-purple-600",
  },
  {
    id: 5,
    slug: "wooden",
    name: "Wooden Toys",
    nameAr: "ألعاب خشبية",
    description: "Classic handcrafted quality",
    descriptionAr: "جودة كلاسيكية مصنوعة يدوياً",
    image: "https://images.unsplash.com/photo-1611649752374-fe4b0e23f3e3?w=600&q=80",
    count: 63,
    color: "from-amber-400 to-amber-600",
  },
  {
    id: 6,
    slug: "stuffed",
    name: "Stuffed Animals",
    nameAr: "الحيوانات المحشوة",
    description: "Soft companions kids will love",
    descriptionAr: "رفاق ناعمون يحبهم الأطفال",
    image: "https://images.unsplash.com/photo-1559181567-c3190ca9d713?w=600&q=80",
    count: 87,
    color: "from-red-400 to-red-600",
  },
];

export const products = [
  {
    id: 1,
    sku: "BRT-EDU-001",
    name: "Rainbow Stacking Rings",
    nameAr: "حلقات التكديس القوسية",
    category: "Educational",
    categorySlug: "educational",
    ageRange: "0-2",
    material: "BPA-Free Plastic",
    dimensions: "30 x 15 cm",
    weight: "350g",
    moq: 100,
    certifications: ["CE", "ASTM", "EN71"],
    description: "Colorful stacking rings that develop fine motor skills, color recognition, and hand-eye coordination in babies and toddlers.",
    descriptionAr: "حلقات تكديس ملونة تطور المهارات الحركية الدقيقة والتمييز بين الألوان وتنسيق اليد والعين لدى الرضع والأطفال الصغار.",
    isFeatured: true,
    isNew: true,
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80",
    ],
  },
  {
    id: 2,
    sku: "BRT-OUT-042",
    name: "Junior Tricycle",
    nameAr: "دراجة ثلاثية العجلات للأطفال",
    category: "Outdoor",
    categorySlug: "outdoor",
    ageRange: "3-5",
    material: "Steel + PP",
    dimensions: "70 x 45 x 55 cm",
    weight: "4.2kg",
    moq: 50,
    certifications: ["CE", "EN71"],
    description: "Durable steel-frame tricycle with adjustable seat, safe handlebar grips, and non-slip pedals.",
    descriptionAr: "دراجة ثلاثية العجلات بإطار فولاذي متين ومقعد قابل للتعديل ومقابض دراجة آمنة ودواسات غير قابلة للانزلاق.",
    isFeatured: true,
    isNew: false,
    images: [
      "https://images.unsplash.com/photo-1566438480900-0609be27a4be?w=600&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    ],
  },
  {
    id: 3,
    sku: "BRT-WOD-018",
    name: "Wooden Block Set 50pcs",
    nameAr: "مجموعة مكعبات خشبية 50 قطعة",
    category: "Wooden",
    categorySlug: "wooden",
    ageRange: "3-5",
    material: "Natural Wood",
    dimensions: "40 x 30 x 12 cm",
    weight: "1.8kg",
    moq: 200,
    certifications: ["CE", "ASTM", "EN71"],
    description: "Premium natural wooden building blocks in multiple shapes and colors for creative construction play.",
    descriptionAr: "مكعبات بناء خشبية طبيعية فاخرة بأشكال وألوان متعددة للعب البناء الإبداعي.",
    isFeatured: true,
    isNew: false,
    images: [
      "https://images.unsplash.com/photo-1611649752374-fe4b0e23f3e3?w=600&q=80",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80",
    ],
  },
  {
    id: 4,
    sku: "BRT-ELC-077",
    name: "Interactive Learning Tablet",
    nameAr: "لوحة تعليمية تفاعلية",
    category: "Electronic",
    categorySlug: "electronic",
    ageRange: "6-8",
    material: "ABS Plastic",
    dimensions: "22 x 15 x 2 cm",
    weight: "420g",
    moq: 100,
    certifications: ["CE", "ASTM", "FCC"],
    description: "Kid-safe learning tablet with 200+ educational games, alphabet, numbers, music and stories in multiple languages.",
    descriptionAr: "لوحة تعليمية آمنة للأطفال تحتوي على أكثر من 200 لعبة تعليمية بالحروف الأبجدية والأرقام والموسيقى والقصص بلغات متعددة.",
    isFeatured: true,
    isNew: true,
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
      "https://images.unsplash.com/photo-1611649752374-fe4b0e23f3e3?w=600&q=80",
    ],
  },
  {
    id: 5,
    sku: "BRT-STF-033",
    name: "Giant Plush Elephant",
    nameAr: "فيل قطيفة عملاق",
    category: "Stuffed Animals",
    categorySlug: "stuffed",
    ageRange: "0-2",
    material: "Polyester + PP Cotton",
    dimensions: "60 x 35 x 40 cm",
    weight: "800g",
    moq: 150,
    certifications: ["CE", "EN71", "ASTM"],
    description: "Soft, huggable giant elephant plush with embroidered details and ultra-soft premium fabric.",
    descriptionAr: "فيل قطيفة ضخم ناعم وقابل للعناق مع تفاصيل مطرزة وقماش فاخر فائق النعومة.",
    isFeatured: false,
    isNew: true,
    images: [
      "https://images.unsplash.com/photo-1559181567-c3190ca9d713?w=600&q=80",
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80",
    ],
  },
  {
    id: 6,
    sku: "BRT-BAB-009",
    name: "Sensory Activity Cube",
    nameAr: "مكعب النشاط الحسي",
    category: "Baby",
    categorySlug: "baby",
    ageRange: "0-2",
    material: "BPA-Free Plastic",
    dimensions: "15 x 15 x 15 cm",
    weight: "280g",
    moq: 200,
    certifications: ["CE", "ASTM", "EN71"],
    description: "5-sided activity cube with buttons, gears, abacus, and spinning elements to stimulate senses.",
    descriptionAr: "مكعب نشاط ذو 5 أوجه مع أزرار وتروس وعداد وعناصر دوارة لتحفيز الحواس.",
    isFeatured: false,
    isNew: false,
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80",
    ],
  },
  {
    id: 7,
    sku: "BRT-OUT-055",
    name: "Sandbox Play Set",
    nameAr: "مجموعة اللعب بالرمل",
    category: "Outdoor",
    categorySlug: "outdoor",
    ageRange: "3-5",
    material: "PP Plastic",
    dimensions: "25 x 20 x 15 cm",
    weight: "600g",
    moq: 100,
    certifications: ["CE", "EN71"],
    description: "Complete beach/sandbox playset with bucket, spade, rake, molds and watering can.",
    descriptionAr: "مجموعة اللعب الكاملة للشاطئ/صندوق الرمل مع دلو وجاروف ومشط وقوالب وناثرة ماء.",
    isFeatured: false,
    isNew: false,
    images: [
      "https://images.unsplash.com/photo-1566438480900-0609be27a4be?w=600&q=80",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80",
    ],
  },
  {
    id: 8,
    sku: "BRT-EDU-022",
    name: "Magnetic Drawing Board",
    nameAr: "لوح الرسم المغناطيسي",
    category: "Educational",
    categorySlug: "educational",
    ageRange: "3-5",
    material: "ABS + Magnetic Sheet",
    dimensions: "30 x 22 cm",
    weight: "350g",
    moq: 150,
    certifications: ["CE", "ASTM", "EN71"],
    description: "Reusable magnetic drawing board with stampers, stylus pen, and colorful doodle area.",
    descriptionAr: "لوح رسم مغناطيسي قابل لإعادة الاستخدام مع طوابع وقلم رسم ومنطقة خربشة ملونة.",
    isFeatured: false,
    isNew: true,
    images: [
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80",
      "https://images.unsplash.com/photo-1611649752374-fe4b0e23f3e3?w=600&q=80",
    ],
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Ahmed Al-Rashid",
    company: "Al-Rashid Toys LLC",
    country: "UAE",
    flag: "🇦🇪",
    rating: 5,
    text: "Best Resource Toys has been our trusted supplier for 5 years. Their quality is consistently excellent and delivery is always on time. Highly recommended for any serious toy distributor.",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    company: "Kids Paradise Inc.",
    country: "USA",
    flag: "🇺🇸",
    rating: 5,
    text: "Outstanding OEM service! They helped us create our private label line from scratch. The attention to safety certifications and quality control is unmatched in the industry.",
  },
  {
    id: 3,
    name: "Mohammed Hassan",
    company: "Hassan Trading",
    country: "Saudi Arabia",
    flag: "🇸🇦",
    rating: 5,
    text: "Competitive pricing with premium quality. Our customers love the educational toys range. The team is very responsive and professional in all dealings.",
  },
  {
    id: 4,
    name: "Elena Petrov",
    company: "ToyWorld Europe",
    country: "Germany",
    flag: "🇩🇪",
    rating: 5,
    text: "Excellent CE certification compliance and product safety standards. We have been importing from them for 3 years with zero quality issues.",
  },
];

export const news = [
  {
    id: 1,
    slug: "new-2025-catalog-launched",
    title: "New 2025 Product Catalog Launched",
    titleAr: "إطلاق كتالوج المنتجات الجديد لعام 2025",
    date: "2025-01-15",
    category: "Company News",
    excerpt: "We are excited to announce the launch of our 2025 product catalog featuring over 500 new items across all categories.",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&q=80",
  },
  {
    id: 2,
    slug: "canton-fair-2025",
    title: "Meet Us at Canton Fair Spring 2025",
    titleAr: "قابلنا في معرض كانتون ربيع 2025",
    date: "2025-01-08",
    category: "Events",
    excerpt: "Visit our booth at the upcoming Canton Fair. Booth number 13.2C15. We will be showcasing all our latest products.",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
  },
  {
    id: 3,
    slug: "new-safety-certifications",
    title: "We Achieved New Safety Certifications",
    titleAr: "حصلنا على شهادات سلامة جديدة",
    date: "2024-12-20",
    category: "Quality",
    excerpt: "Proud to announce that our entire product line has received updated CE and ASTM F963 certifications for 2025.",
    image: "https://images.unsplash.com/photo-1611649752374-fe4b0e23f3e3?w=600&q=80",
  },
];

export const stats = [
  { label: "Years Experience", value: 20, suffix: "+" },
  { label: "Products", value: 5000, suffix: "+" },
  { label: "Countries", value: 50, suffix: "+" },
  { label: "Happy Clients", value: 1000, suffix: "+" },
];
