ALTER TABLE "users"
ADD COLUMN "permissions" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

UPDATE "users"
SET "permissions" = ARRAY[
  'MANAGE_USERS',
  'MANAGE_APPROVALS',
  'MANAGE_PRODUCTS',
  'MANAGE_CUSTOMERS',
  'MANAGE_INVOICES',
  'MANAGE_VOUCHERS',
  'VIEW_REPORTS',
  'MANAGE_SETTINGS'
]
WHERE "role" = 'ADMIN';
