import { useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Copy, ExternalLink, MonitorSmartphone, RefreshCw } from "lucide-react"
import { getSettings, rotateKioskToken, updateSettings } from "../api/endpoints"
import { Button } from "./ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card"
import { Input } from "./ui/input"
import { toast } from "./ui/use-toast"
// No window.open in Tauri — an external link must go through the shell.
import { openExternalUrl } from "../utils/download"

/**
 * «الكشك» — the screen the shop stands in its own showroom.
 *
 * The link IS the credential, so three things are deliberate here:
 *  - the switch kills every copy of the link at once, which is what the shop
 *    reaches for when the tablet walks away;
 *  - the link is generated by the server, never typed here;
 *  - generating a new one is explicitly labelled as killing the old one, so
 *    nobody discovers that by pressing a button called «تحديث».
 */
export function KioskSettingsCard() {
  const qc = useQueryClient()
  const settings = useQuery({ queryKey: ["settings"], queryFn: getSettings })
  const [copied, setCopied] = useState(false)
  const [title, setTitle] = useState<string | null>(null)

  const save = useMutation({
    mutationFn: (patch: Record<string, unknown>) => updateSettings(patch),
    onSuccess: () => { toast({ title: "تم الحفظ" }); void qc.invalidateQueries({ queryKey: ["settings"] }) },
    onError: () => toast({ title: "تعذر الحفظ", variant: "destructive" }),
  })

  const rotate = useMutation({
    mutationFn: rotateKioskToken,
    onSuccess: () => {
      toast({ title: "صار عندك رابط جديد — الرابط القديم ما يفتح بعد" })
      void qc.invalidateQueries({ queryKey: ["settings"] })
    },
    onError: () => toast({ title: "تعذر توليد الرابط", variant: "destructive" }),
  })

  const token = settings.data?.kioskToken ?? ""
  const enabled = settings.data?.kioskEnabled === true
  // The shop's public origin, same source the auction and count links use —
  // the tablet opens this link, and the tablet is not on this machine.
  const configured = settings.data?.catalogPublicUrl?.trim().replace(/\/catalog.*$/, "").replace(/\/$/, "")
  const link = token ? `${configured || window.location.origin}/kiosk/${token}` : ""

  async function copy() {
    try {
      await navigator.clipboard.writeText(link)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 2000)
    } catch {
      toast({ title: "ما قدرت أنسخ — علّم الرابط وانسخه بيدك", variant: "destructive" })
    }
  }

  return (
    <Card>
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-base">
          <MonitorSmartphone className="h-5 w-5 text-slate-600" />
          الكشك — شاشة الطلب بالمحل
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <p className="text-xs text-slate-500">
          شاشة تحطها بالمحل. الزبون يختار بضاعته، يكتب اسمه ورقمه، والطلب يوصلك بالموافقات
          مثل أي طلب كتلوك — ما ينكتب بيع لحاله.
        </p>

        <label className="flex items-start gap-3 rounded-xl border border-slate-200 p-3">
          <input
            type="checkbox"
            checked={enabled}
            onChange={(e) => save.mutate({ kioskEnabled: e.target.checked })}
            className="mt-0.5 h-4 w-4 shrink-0 accent-emerald-600"
          />
          <span>
            <span className="block text-sm font-bold text-slate-800">شغّل الكشك</span>
            <span className="block text-xs text-slate-500">
              إطفاؤه يقفل كل الروابط فوراً — الشاشة ما تفتح شي.
            </span>
          </span>
        </label>

        <div className="rounded-xl border border-slate-200 p-3">
          <span className="mb-2 block text-sm font-bold text-slate-800">الأسعار المعروضة</span>
          <div className="flex gap-2">
            {(["WHOLESALE", "CARTON"] as const).map((mode) => (
              <Button
                key={mode}
                size="sm"
                variant={(settings.data?.kioskPriceMode ?? "WHOLESALE") === mode ? "default" : "outline"}
                onClick={() => save.mutate({ kioskPriceMode: mode })}
              >
                {mode === "WHOLESALE" ? "سعر القطعة" : "سعر الكارتون"}
              </Button>
            ))}
          </div>
          <p className="mt-2 text-xs text-slate-500">
            بوضع الكارتون ما تظهر إلا البضاعة الي عندها كارتون كامل.
          </p>
        </div>

        <div className="rounded-xl border border-slate-200 p-3">
          <span className="mb-2 block text-sm font-bold text-slate-800">عنوان الشاشة</span>
          <div className="flex gap-2">
            <Input
              value={title ?? settings.data?.kioskTitle ?? ""}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="اسم المحل"
              maxLength={80}
            />
            <Button
              size="sm"
              disabled={title === null || title === (settings.data?.kioskTitle ?? "")}
              onClick={() => { save.mutate({ kioskTitle: title ?? "" }); setTitle(null) }}
            >
              حفظ
            </Button>
          </div>
        </div>

        <div className="rounded-xl border border-slate-200 p-3">
          <span className="mb-2 block text-sm font-bold text-slate-800">رابط الشاشة</span>
          {link ? (
            <>
              <div className="flex gap-2">
                <Input value={link} readOnly dir="ltr" onFocus={(e) => e.currentTarget.select()} />
                <Button size="sm" variant="outline" onClick={copy}>
                  <Copy className="ml-1 h-4 w-4" />
                  {copied ? "انتسخ" : "انسخ"}
                </Button>
                <Button size="sm" variant="outline" onClick={() => void openExternalUrl(link)}>
                  <ExternalLink className="ml-1 h-4 w-4" />
                  افتح
                </Button>
              </div>
              <p className="mt-2 text-xs text-slate-500">
                افتحه بمتصفح التابلت وخلّه بوضع ملء الشاشة. نفس الرابط يشتغل بالبرنامج.
              </p>
            </>
          ) : (
            <p className="text-xs text-slate-500">ما عندك رابط بعد — ولّد واحد.</p>
          )}
          <Button
            className="mt-3"
            size="sm"
            variant="outline"
            disabled={rotate.isPending}
            onClick={() => {
              if (token && !window.confirm("الرابط القديم راح يبطّل يشتغل. أولّد رابط جديد؟")) return
              rotate.mutate()
            }}
          >
            <RefreshCw className="ml-1 h-4 w-4" />
            {token ? "ولّد رابط جديد (يلغي القديم)" : "ولّد رابط"}
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}
