/**
 * «الكشك» — the screen standing inside the shop.
 *
 * A customer walks up to a tablet (or the shop's own PC), picks what they
 * want, writes their name and phone, and the order lands in the shop's
 * approvals exactly like a catalog order. Nothing here is a new sales path:
 * it is the wholesale catalog with the browsing parts removed and a bigger
 * finger target, so an order placed at the kiosk goes through the same stock
 * checks, the same server-side prices and the same approval as every other
 * catalog order.
 *
 * The link is the credential. The token is generated by the shop, stored in
 * settings, and only ever written by `rotateKioskToken` — a settings save can
 * never set it, so a copied link cannot be pointed somewhere else. Turning
 * `kioskEnabled` off makes every kiosk link dead immediately, which is what
 * the shop reaches for when the tablet walks away.
 */

import crypto from "crypto";
import { AppError } from "../utils/app-error";
import { getSettings, updateSettings } from "./settings.service";
import {
  listVisitorCatalogProducts,
  submitGuestCatalogOrder,
  type GuestCatalogOrderInput,
} from "./catalog.service";
import prisma from "../config/database";

export type KioskPriceMode = "WHOLESALE" | "CARTON";

/**
 * Validates the link and returns what the screen is allowed to show.
 *
 * Compared in constant time: the token is a bearer credential on a device
 * that sits in a public room, and a timing oracle on it is free to measure.
 */
export async function requireKiosk(token: string) {
  const settings = await getSettings();
  const stored = String(settings.kioskToken ?? "");
  const given = String(token ?? "");
  const ok =
    settings.kioskEnabled === true &&
    stored.length > 0 &&
    stored.length === given.length &&
    crypto.timingSafeEqual(Buffer.from(stored), Buffer.from(given));

  if (!ok) {
    throw new AppError("شاشة الكشك غير مفعّلة أو الرابط غير صحيح", 403, "KIOSK_DISABLED");
  }

  return {
    storeName: String(settings.storeName ?? ""),
    title: String(settings.kioskTitle ?? "").trim(),
    priceMode: (settings.kioskPriceMode === "CARTON" ? "CARTON" : "WHOLESALE") as KioskPriceMode,
  };
}

/**
 * The grid. Prices are always shown: the person is standing in the shop, in
 * front of the goods and their price tags — hiding them here would only make
 * the screen useless.
 */
export async function listKioskProducts(token: string) {
  const kiosk = await requireKiosk(token);
  return listVisitorCatalogProducts({ pricesUnlocked: true, priceMode: kiosk.priceMode });
}

/**
 * Thumbnails for the cards about to be drawn, in one request.
 *
 * The grid deliberately ships without pictures — a few hundred base64
 * thumbnails is several megabytes on open — so the screen asks for the ones
 * it can see. Same trick the catalog already uses.
 */
export async function kioskThumbnails(token: string, productIds: string[]) {
  await requireKiosk(token);
  const ids = [...new Set(productIds)].slice(0, 120);
  if (ids.length === 0) return {} as Record<string, string | null>;

  const rows = await prisma.product.findMany({
    where: { id: { in: ids }, deletedAt: null },
    select: { id: true, thumbnailUrl: true },
  });

  const out: Record<string, string | null> = {};
  for (const row of rows) out[row.id] = row.thumbnailUrl;
  return out;
}

export async function kioskProductImage(token: string, productId: string) {
  await requireKiosk(token);
  const product = await prisma.product.findFirst({
    where: { id: productId, deletedAt: null },
    select: { imageUrl: true },
  });
  return product?.imageUrl ?? null;
}

/**
 * An order from the screen. Same pipeline as a guest catalog order — same
 * stock checks, same server-computed prices, same approval — with the kiosk
 * token standing in for the browsing gate, because the shop's own screen is
 * not "anonymous browsing" and must keep working when that switch is off.
 */
export async function submitKioskOrder(
  token: string,
  input: Omit<GuestCatalogOrderInput, "priceMode">,
) {
  const kiosk = await requireKiosk(token);
  return submitGuestCatalogOrder({ ...input, priceMode: kiosk.priceMode, kiosk: true });
}

/**
 * Generates a fresh link and, on the same save, turns the kiosk on. The old
 * link stops working the moment this returns — that is the point of the
 * button.
 */
export async function rotateKioskToken() {
  const token = crypto.randomBytes(24).toString("base64url");
  await updateSettings({ kioskToken: token, kioskEnabled: true });
  return token;
}
