package com.inventory.ui.navigation

object Routes {
    const val Splash = "splash"
    const val Login = "login"
    const val Dashboard = "dashboard"
    const val Users = "users"
    const val Approvals = "approvals"
    const val Products = "products"
    const val ProductScanner = "products/scan"
    const val ProductAdd = "products/new?qrCode={qrCode}"
    const val ProductDetail = "products/{productId}"
    const val ProductEdit = "products/{productId}/edit"
    const val ProductMovement = "products/{productId}/movement"
    const val Customers = "customers"
    const val CustomerAdd = "customers/new"
    const val CustomerDetail = "customers/{customerId}"
    const val CustomerStatement = "customers/{customerId}/statement"
    const val Receipt = "receipts/new?customerId={customerId}"
    const val Invoices = "invoices"
    const val InvoiceCreate = "invoices/new"
    const val VoucherCreate = "vouchers/new"
    const val InvoiceDetail = "invoices/{invoiceId}"
    const val DashboardReport = "reports/dashboard"
    const val Reports = "reports"
    const val Settings = "settings"
    const val Notifications = "notifications"
    const val AccountLookup = "account-lookup"

    fun productDetail(productId: String) = "products/$productId"
    fun productEdit(productId: String) = "products/$productId/edit"
    fun productAdd(qrCode: String = "") = "products/new?qrCode=$qrCode"
    fun productMovement(productId: String) = "products/$productId/movement"
    fun customerDetail(customerId: String) = "customers/$customerId"
    fun customerStatement(customerId: String) = "customers/$customerId/statement"
    fun receipt(customerId: String = "") = "receipts/new?customerId=$customerId"
    fun invoiceDetail(invoiceId: String) = "invoices/$invoiceId"
}
