package com.inventory.ui.navigation

object Routes {
    const val Splash = "splash"
    const val Login = "login"
    const val Dashboard = "dashboard"
    const val Users = "users"
    const val Approvals = "approvals"
    const val Products = "products"
    const val ProductScanner = "products/scan"
    const val ProductScannerInvoice = "products/scan-invoice"
    const val ProductAdd = "products/new?qrCode={qrCode}&name={name}"
    const val ProductDetail = "products/{productId}"
    const val ProductEdit = "products/{productId}/edit"
    const val ProductMovement = "products/{productId}/movement"
    const val Customers = "customers"
    const val CustomerAdd = "customers/new"
    const val CustomerDetail = "customers/{customerId}"
    const val CustomerStatement = "customers/{customerId}/statement"
    const val Receipt = "receipts/new?customerId={customerId}"
    const val Invoices = "invoices"
    const val InvoiceCreate = "invoices/new"
    const val Vouchers = "vouchers"
    const val VoucherCreate = "vouchers/new"
    const val InvoiceDetail = "invoices/{invoiceId}"
    const val InvoiceEdit = "invoices/{invoiceId}/edit"
    const val VoucherEdit = "vouchers/{voucherId}/edit"
    const val DashboardReport = "reports/dashboard"
    const val Reports = "reports"
    const val Settings = "settings"
    const val Notifications = "notifications"
    const val AccountLookup = "account-lookup"
    const val VoiceInvoice  = "voice-invoice"
    const val Agent = "agent"
    const val CatalogManagement = "catalog-management"
    const val Operations = "operations"
    const val Pos = "operations/pos"
    const val Returns = "operations/returns"
    const val Quotations = "operations/quotations"
    const val QuotationCreate = "operations/quotations/new"
    const val Transfers = "operations/transfers"
    const val Branches = "operations/branches"
    const val Coupons = "operations/coupons"
    const val AuditLogs = "operations/audit-logs"

    fun productDetail(productId: String) = "products/$productId"
    fun productEdit(productId: String) = "products/$productId/edit"
    fun productAdd(qrCode: String = "", name: String = "") = "products/new?qrCode=${android.net.Uri.encode(qrCode)}&name=${android.net.Uri.encode(name)}"
    fun productMovement(productId: String) = "products/$productId/movement"
    fun customerDetail(customerId: String) = "customers/$customerId"
    fun customerStatement(customerId: String) = "customers/$customerId/statement"
    fun receipt(customerId: String = "") = "receipts/new?customerId=$customerId"
    fun invoiceDetail(invoiceId: String) = "invoices/$invoiceId"
    fun invoiceEdit(invoiceId: String) = "invoices/$invoiceId/edit"
    fun voucherEdit(voucherId: String) = "vouchers/$voucherId/edit"
}
