import { Router } from "express";
import approvalsRoutes from "./approvals.routes";
import agentRoutes from "./agent.routes";
import auditLogsRoutes from "./audit-logs.routes";
import branchesRoutes from "./branches.routes";
import authRoutes from "./auth.routes";
import couponsRoutes from "./coupons.routes";
import customersRoutes from "./customers.routes";
import invoicesRoutes from "./invoices.routes";
import messageTemplatesRoutes from "./message-templates.routes";
import notificationsRoutes from "./notifications.routes";
import publicRoutes from "./public.routes";
import productsRoutes from "./products.routes";
import quotationsRoutes from "./quotations.routes";
import reportsRoutes from "./reports.routes";
import settingsRoutes from "./settings.routes";
import usersRoutes from "./users.routes";
import vouchersRoutes from "./vouchers.routes";
import transfersRoutes from "./transfers.routes";
import whatsappRoutes from "./whatsapp.routes";
import voiceRoutes from "./voice.routes";
import ocrRoutes from "./ocr.routes";
import catalogManagementRoutes from "./catalog-management.routes";
import orderPreparationsRoutes from "./order-preparations.routes";

const router = Router();

router.use("/public", publicRoutes);
router.use("/agent", agentRoutes);
router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/approvals", approvalsRoutes);
router.use("/audit-logs", auditLogsRoutes);
router.use("/branches", branchesRoutes);
router.use("/customers", customersRoutes);
router.use("/coupons", couponsRoutes);
router.use("/products", productsRoutes);
router.use("/quotations", quotationsRoutes);
router.use("/invoices", invoicesRoutes);
router.use("/vouchers", vouchersRoutes);
router.use("/transfers", transfersRoutes);
router.use("/reports", reportsRoutes);
router.use("/whatsapp", whatsappRoutes);
router.use("/settings", settingsRoutes);
router.use("/message-templates", messageTemplatesRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/voice", voiceRoutes);
router.use("/ocr", ocrRoutes);
router.use("/catalog-management", catalogManagementRoutes);
router.use("/order-preparations", orderPreparationsRoutes);

export default router;
