import { Router } from "express";
import approvalsRoutes from "./approvals.routes";
import agentRoutes from "./agent.routes";
import auditLogsRoutes from "./audit-logs.routes";
import branchesRoutes from "./branches.routes";
import authRoutes from "./auth.routes";
import couponsRoutes from "./coupons.routes";
import customersRoutes from "./customers.routes";
import invoicesRoutes from "./invoices.routes";
import messageTemplatesRoutes from "./message-templates.routes";
import notificationsRoutes from "./notifications.routes";
import publicRoutes from "./public.routes";
import productsRoutes from "./products.routes";
import quotationsRoutes from "./quotations.routes";
import reportsRoutes from "./reports.routes";
import settingsRoutes from "./settings.routes";
import usersRoutes from "./users.routes";
import vouchersRoutes from "./vouchers.routes";
import transfersRoutes from "./transfers.routes";
import whatsappRoutes from "./whatsapp.routes";
import voiceRoutes from "./voice.routes";
import ocrRoutes from "./ocr.routes";
import catalogManagementRoutes from "./catalog-management.routes";
import orderPreparationsRoutes from "./order-preparations.routes";
import stocktakeRoutes from "./stocktake.routes";
import catalogCategoryRoutes from "./catalog-category.routes";
import licenseRoutes from "./license.routes";
import clientsRoutes from "./clients.routes";
import paymentsRoutes from "./payments.routes";
import retailCatalogRoutes from "./retail-catalog.routes";
import realtimeRoutes from "./realtime.routes";
import tenantInfoRoutes from "./tenant-info.routes";
import stockLossRoutes from "./stock-loss.routes";
import campaignsRoutes from "./campaigns.routes";
import prospectsRoutes from "./prospects.routes";
import inboundMessagesRoutes from "./inbound-messages.routes";
import healthRoutes from "./health.routes";
import errorLogsRoutes from "./error-logs.routes";

const router = Router();

router.use("/tenant-info", tenantInfoRoutes);
router.use("/public", publicRoutes);
router.use("/realtime", realtimeRoutes);
router.use("/agent", agentRoutes);
router.use("/auth", authRoutes);
router.use("/users", usersRoutes);
router.use("/approvals", approvalsRoutes);
router.use("/audit-logs", auditLogsRoutes);
router.use("/branches", branchesRoutes);
router.use("/customers", customersRoutes);
router.use("/coupons", couponsRoutes);
router.use("/products", productsRoutes);
router.use("/quotations", quotationsRoutes);
router.use("/invoices", invoicesRoutes);
router.use("/vouchers", vouchersRoutes);
router.use("/transfers", transfersRoutes);
router.use("/reports", reportsRoutes);
router.use("/whatsapp", whatsappRoutes);
router.use("/settings", settingsRoutes);
router.use("/message-templates", messageTemplatesRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/voice", voiceRoutes);
router.use("/ocr", ocrRoutes);
router.use("/catalog-management", catalogManagementRoutes);
router.use("/order-preparations", orderPreparationsRoutes);
router.use("/stocktake", stocktakeRoutes);
router.use("/catalog-categories", catalogCategoryRoutes);
router.use("/license", licenseRoutes);
router.use("/clients", clientsRoutes);
router.use("/payments", paymentsRoutes);
router.use("/retail-catalog", retailCatalogRoutes);
router.use("/stock-losses", stockLossRoutes);
router.use("/campaigns", campaignsRoutes);
router.use("/prospects", prospectsRoutes);
router.use("/inbound-messages", inboundMessagesRoutes);
router.use("/health", healthRoutes);
router.use("/error-logs", errorLogsRoutes);

export default router;
